'use client'

import React, { Suspense, useEffect, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { AuthComponent, SignupData } from "@/components/ui/sign-up"
import { createClient } from '@/lib/supabase/client'
import { signup, login, completeProfile, resetPassword, resendVerificationEmail } from './actions'

// ─── Email Verified Success Popup ───────────────────────────────────────
// Appears automatically when ?verified=true is in the URL.
// Stays for 5 seconds then smoothly fades out.
function EmailVerifiedPopup() {
  const [visible, setVisible] = useState(true)
  const [fading, setFading] = useState(false)

  useEffect(() => {
    // Begin fade-out after 5 seconds
    const fadeTimer = setTimeout(() => setFading(true), 5000)
    // Fully remove after fade animation (5s + 0.5s transition)
    const removeTimer = setTimeout(() => setVisible(false), 5500)
    return () => {
      clearTimeout(fadeTimer)
      clearTimeout(removeTimer)
    }
  }, [])

  if (!visible) return null

  return (
    <div
      style={{
        position: 'fixed',
        top: '24px',
        left: '50%',
        transform: 'translateX(-50%)',
        zIndex: 9999,
        opacity: fading ? 0 : 1,
        transition: 'opacity 0.5s ease',
        pointerEvents: 'none',
      }}
    >
      <div style={{
        background: 'linear-gradient(135deg, rgba(16,24,32,0.97) 0%, rgba(10,30,20,0.97) 100%)',
        border: '1px solid rgba(52,211,153,0.35)',
        borderRadius: '16px',
        padding: '20px 28px',
        minWidth: '320px',
        maxWidth: '440px',
        boxShadow: '0 8px 40px rgba(0,0,0,0.5), 0 0 0 1px rgba(52,211,153,0.1)',
        backdropFilter: 'blur(16px)',
        display: 'flex',
        alignItems: 'flex-start',
        gap: '14px',
      }}>
        {/* Icon */}
        <div style={{
          width: '40px',
          height: '40px',
          borderRadius: '50%',
          background: 'rgba(52,211,153,0.15)',
          border: '1.5px solid rgba(52,211,153,0.4)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          flexShrink: 0,
          fontSize: '20px',
        }}>
          🎉
        </div>
        {/* Text */}
        <div>
          <p style={{ margin: 0, fontWeight: 700, fontSize: '15px', color: '#34d399', letterSpacing: '-0.01em' }}>
            Email Verified Successfully
          </p>
          <p style={{ margin: '4px 0 0', fontSize: '13px', color: 'rgba(255,255,255,0.65)', lineHeight: 1.5 }}>
            Your email has been verified successfully.<br />
            You can now log in to your account.
          </p>
        </div>
      </div>
    </div>
  )
}
// ──────────────────────────────────────────────────────────────────────────────


const CustomLogo = () => (
  <div className="bg-blue-600 rounded-lg p-2">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-6 h-6 text-white">
      <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
    </svg>
  </div>
);

function LoginContent() {
  const searchParams = useSearchParams()
  const modeParam = searchParams.get('mode')
  const isCompleteMode = modeParam === 'complete'
  // NOTE: mode=signup is FORBIDDEN per auth spec §8 — it is never generated by any redirect.
  //       Only mode=complete (Google profile onboarding) is a valid mode value.
  const isVerified = searchParams.has('verified')

  const [defaultEmail, setDefaultEmail] = useState('')
  const [defaultName, setDefaultName] = useState('')
  const [isLoading, setIsLoading] = useState(true)
  const [loadingError, setLoadingError] = useState<string | null>(null)
  const [pendingVerificationEmail, setPendingVerificationEmail] = useState('')
  const [debugText, setDebugText] = useState('Initializing (v2)...')
  const [supabaseClient, setSupabaseClient] = useState<any>(null)

  useEffect(() => {
    let supabase: any;
    try {
      supabase = createClient();
      setSupabaseClient(supabase);
    } catch (e: any) {
      console.error('[Auth] Failed to initialize Supabase client:', e);
    }

    // ─── EARLY AUTH GUARD ──────────────────────────────────────────────────
    // If a confirmed user (Google OR confirmed email) lands on /login for any
    // reason — including carrying ?mode=signup&verified=true from a stale
    // redirect — send them to dashboard immediately before rendering any form.
    // EXCEPTION: mode=complete is the Google profile-completion onboarding flow.
    if (!isCompleteMode && supabase) {
      supabase.auth.getUser().then(({ data }: any) => {
        const u = data?.user
        if (!u) return // not logged in, let login page render normally

        const provider = u.app_metadata?.provider
        const isGoogleUser = provider !== 'email'
        const isConfirmedEmail = provider === 'email' && !!u.email_confirmed_at

        console.log('[AUTH DEBUG login/page]', {
          userEmail: u.email,
          provider,
          isGoogleUser,
          isConfirmedEmail,
          modeParam,
          isVerified,
          redirectTarget: (isGoogleUser || isConfirmedEmail) ? '/dashboard' : 'stay',
        })

        if (isGoogleUser || isConfirmedEmail) {
          // Confirmed user — must never see signup/create-account form
          console.log('[AUTH DEBUG login/page] Confirmed user detected — redirecting to /dashboard')
          window.location.replace('/dashboard')
        }
      }).catch(() => {
        // Ignore — if getUser() fails just render the login form normally
      })
    }
    // ──────────────────────────────────────────────────────────────────────

    let pendingEmail = null
    try {
      pendingEmail = sessionStorage.getItem('pendingVerificationEmail')
    } catch (e) {
      console.warn('[Auth] sessionStorage access denied:', e)
    }

    if (pendingEmail) {
      if (isVerified) {
        try {
          sessionStorage.removeItem('pendingVerificationEmail')
        } catch (e) {
          console.warn('[Auth] sessionStorage access denied:', e)
        }
        pendingEmail = null
      } else {
        setPendingVerificationEmail(pendingEmail)
        setIsLoading(false)
        return
      }
    }

    // Check for Supabase hash errors (e.g. #error_code=otp_expired)
    if (typeof window !== 'undefined' && window.location.hash) {
      const hashParams = new URLSearchParams(window.location.hash.substring(1))
      const errorCode = hashParams.get('error_code')
      if (errorCode === 'otp_expired') {
        window.history.replaceState(null, '', window.location.pathname + window.location.search)
        setLoadingError('Verification link expired or already used. If you or your email scanner already clicked it, your email might be verified! Try logging in below or wait 1 minute to request a new link.')
        setIsLoading(false)
        return
      }
    }

    if (!isCompleteMode) {
      setIsLoading(false)
      return
    }

    let isMounted = true
    const timeoutId = setTimeout(() => {
      if (isMounted) setIsLoading(false)
    }, 5000)

    if (supabase) {
      supabase.auth.getUser().then(({ data, error }: any) => {
        if (!isMounted) return
        clearTimeout(timeoutId)
        
        const user = data?.user
        if (user) {
          setDefaultEmail(user.email || '')
          const metaName = user.user_metadata?.full_name || user.user_metadata?.name || ''
          setDefaultName(metaName)
        }
        setIsLoading(false)
      }).catch(() => {
        if (!isMounted) return
        clearTimeout(timeoutId)
        setIsLoading(false)
      })
    } else {
      setIsLoading(false)
    }

    return () => {
      isMounted = false
      clearTimeout(timeoutId)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isCompleteMode])

  const handleGoogleSignIn = async () => {
    if (!supabaseClient) return;
    await supabaseClient.auth.signInWithOAuth({
      provider: 'google',
      options: { redirectTo: `${window.location.origin}/auth/callback` },
    })
  }

  const handleEmailSubmit = async (data: SignupData | { email: string; password: string }) => {
    if (!('fullName' in data)) {
      const result = await login(data.email, data.password)
      if (result.type === 'check_email') return { error: null, type: 'check_email' }
      return { error: result.error }
    }
    const signupData = data as SignupData
    if (isCompleteMode) {
      const result = await completeProfile({
        fullName: signupData.fullName, username: signupData.username, mobileNumber: signupData.mobileNumber, linkedinUrl: signupData.linkedinUrl, avatarId: signupData.avatarId,
      })
      if (!result.error) {
        // Profile saved successfully — go straight to dashboard
        window.location.href = '/dashboard'
        return { error: null }
      }
      return result.error
    }
    const result = await signup({
      email: signupData.email, password: signupData.password, fullName: signupData.fullName, username: signupData.username, mobileNumber: signupData.mobileNumber, linkedinUrl: signupData.linkedinUrl, avatarId: signupData.avatarId,
    })
    if (result.error && result.error.toLowerCase().includes('already registered')) return { error: 'Account has been already created with this email.' }
    // For email signups, profile is created in /auth/callback after the user verifies their email.
    // Do NOT call completeProfile here — the auth user may not be confirmed yet (FK constraint).
    if (result.type === 'check_email') return { error: null, type: 'check_email' }
    return { error: result.error }
  }

  const handleResetPassword = async (email: string) => {
    const result = await resetPassword(email)
    return result.error
  }

  const handleResendEmail = async (email: string) => {
    const result = await resendVerificationEmail(email)
    return result.error
  }
  if (loadingError) {
    return (
      <div className="min-h-screen bg-black flex flex-col items-center justify-center text-white p-4">
        <div className="bg-red-900/20 text-red-400 border border-red-900/50 p-6 rounded-lg text-center max-w-md">
          <p className="font-semibold mb-2">Session Error</p>
          <p className="text-sm opacity-90">{loadingError}</p>
          <button 
            onClick={() => window.location.reload()}
            className="mt-6 px-6 py-2 bg-white text-black rounded-full text-sm font-bold hover:bg-neutral-200 transition-colors"
          >
            Refresh Page
          </button>
        </div>
      </div>
    )
  }

  if (isLoading) {
    return (
      <div className="min-h-screen bg-black flex flex-col items-center justify-center text-white font-mono p-4">
        <div className="w-8 h-8 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mb-4" />
        <p className="text-lg mb-2">Loading...</p>
        <p className="text-xs text-neutral-500 whitespace-pre-wrap text-center max-w-md">
          {debugText}
        </p>
      </div>
    )
  }

  return (
    <>
      {/* Verification success popup — fires only when ?verified=true (email users only), auto-dismisses after 5s */}
      {/* SPEC §4 §8: Google users NEVER receive ?verified=true — safe to render unconditionally on that param */}
      {isVerified && !isCompleteMode && <EmailVerifiedPopup />}
      <AuthComponent
        logo={<CustomLogo />}
        brandName="PostForge AI"
        onGoogleSignIn={handleGoogleSignIn}
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        onEmailSubmit={handleEmailSubmit as any}
        onResetPassword={handleResetPassword}
        onResendEmail={handleResendEmail}
        initialMode={isCompleteMode ? 'complete' : 'initial'}
        defaultEmail={defaultEmail}
        defaultName={defaultName}
        pendingVerificationEmail={pendingVerificationEmail}
        isVerified={false}
      />
    </>
  )
}

export default function LoginPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-black" />}>
      <LoginContent />
    </Suspense>
  )
}
